kgc_model: data/kgc/cde.m_8051991_27/distmult/trial-0012
split_dataset: data/split/cde.m_8051991_27

optimizer: adam
optimizer_args:
  lr: 1.0e-04

projector_args:
  input_dims: 768
  output_dims: 500
