#
#          RYN TEXT MAPPER CONFIGURATION
#    -----------------------------------------
#
#        see the default.yml for comments
#
text_encoder: bert-base-cased

split_text_dataset: false

kgc_model: data/kgc/vll.fb15k237-owe_2041992/distmult/trial-0046
split_dataset: data/split/vll.fb15k237-owe_2041992
text_dataset: data/text/data/vll.fb15k237-owe_2041992/entity2wikidata.json/bert-base-cased.1.768.clean

wandb_args:
  project: ryn-text
  log_model: false

trainer_args:
  gpus: 1
  max_epochs: 2000
  check_val_every_n_epoch: 2
  fast_dev_run: false
  distributed_backend: horovod
  accumulate_grad_batches: 10
  gradient_clip_val: 1
  replace_sampler_ddp: false
  log_every_n_steps: 5

checkpoint_args:
  mode: max
  monitor: inductive/hits_at_k/both/avg/10
  save_top_k: 10

early_stopping: true
early_stopping_args:
  monitor: inductive/hits_at_k/both/avg/10
  mode: max
  min_delta: 0.0001
  patience: 5

dataloader_train_args:
  num_workers: 0
  shuffle: True

dataloader_valid_args:
  num_workers: 0

dataloader_test_args:
  num_workers: 0

optimizer: adam
optimizer_args:
  lr: 1.0e-05

projector_args:
  input_dims: 768
  output_dims: 450
