evaluator:
  cls: RankBasedEvaluator
general:
  seed: null
loss:
  cls: MarginRankingLoss
  margin: 1.0
  reduction: mean
model:
  cls: DistMult
  embedding_dim:
    high: 500
    initial: 250
    log: false
    low: 50
    step: 50
  preferred_device: cuda
optimizer:
  cls: Adagrad
  lr:
    high: 0.1
    initial: 0.01
    log: true
    low: 0.001
    step: null
optuna:
  maximise: true
  trials: 100
regularizer:
  cls: LpRegularizer
  normalize: true
  p: 2.0
  weight:
    high: 0.1
    initial: null
    log: true
    low: 0.01
    step: null
sampler:
  cls: BasicNegativeSampler
  num_negs_per_pos:
    high: 50
    initial: 25
    log: false
    low: 1
    step: 1
stopper:
  cls: EarlyStopper
  frequency: 1
  patience: 10
  relative_delta: 0.0001
tracker:
  cls: wandb
  offline: false
  project: irtm-keen
  reinit: true
training:
  batch_size: 200
  num_epochs: 2000
training_loop:
  cls: SLCWATrainingLoop
