#
#          RYN TEXT MAPPER CONFIGURATION
#    -----------------------------------------
#
#        see the default.yml for comments
#
valid_split: 0.9

wandb_args:
  project: ryn-text
  log_model: False

trainer_args:
  gpus: 1
  max_epochs: 50
  fast_dev_run: False
  distributed_backend: horovod
  accumulate_grad_batches: 5
  gradient_clip_val: 1

checkpoint_args:
  monitor: inductive.hits@10/dataloader_idx_2
  save_top_k: 10

dataloader_train_args:
  batch_size: 200
  num_workers: 0
  shuffle: True

dataloader_valid_args:
  batch_size: 225
  num_workers: 0

dataloader_test_args:
  batch_size: 250
  num_workers: 0

optimizer: adam
optimizer_args:
  lr: 0.00001

text_encoder: bert-base-cased
freeze_text_encoder: True

aggregator: max 1
projector: affine 1
projector_args:
  input_dims: 768
  output_dims: 450

comparator: euclidean 1
