# 11GB GPU RAM configuration
# - used for split seed=30061990 ratio=0.9 with 30 sentences
# - text encoder must be frozen
# - tested with GTX 1080 TI

dataloader_train_args:
  batch_size: 200

dataloader_valid_args:
  batch_size: 225

dataloader_test_args:
  batch_size: 250
