#
#          IRTM TEXT MAPPER CONFIGURATION
#    -----------------------------------------
#
#         see the default.yml for comments

valid_split: 0.9

wandb_args:
  project: irtm-text-proto
  log_model: False

trainer_args:
  gpus: 1
  max_epochs: 5
  fast_dev_run: False
  distributed_backend: horovod
  accumulate_grad_batches: 1
  gradient_clip_val: 1
  log_every_n_steps: 1
  replace_sampler_ddp: False

checkpoint_args:
  monitor: inductive/hits_at_k/both/avg/10
  save_top_k: 2

sampler: node degree
sampler_args:
  num_samples: x1
  replacement: True

dataloader_train_args:
  num_workers: 0
  shuffle: False

dataloader_valid_args:
  num_workers: 0

dataloader_test_args:
  num_workers: 0

optimizer: adam
optimizer_args:
  lr: 0.00001

text_encoder: bert-base-cased
freeze_text_encoder: True

aggregator: cls 1
projector: affine 1
projector_args:
  input_dims: 768
  output_dims: 500

comparator: euclidean 1
out: data/test/{text_dataset}/
