#
#          RYN TEXT MAPPER CONFIGURATION
#    -----------------------------------------
#
#        see the default.yml for comments

valid_split: 0.9
wandb_args:
  project: ryn-text-proto
  log_model: False

trainer_args:
  gpus: 1
  max_epochs: 5
  fast_dev_run: False
  distributed_backend: horovod
  accumulate_grad_batches: 1
  gradient_clip_val: 1
  log_every_n_steps: 1

checkpoint_args:
  monitor: inductive.hits@10/dataloader_idx_2
  save_top_k: 2

dataloader_train_args:
  num_workers: 0
  shuffle: True

dataloader_valid_args:
  num_workers: 0

dataloader_test_args:
  num_workers: 0

optimizer: adam
optimizer_args:
  lr: 0.000005

text_encoder: bert-base-cased
freeze_text_encoder: True

aggregator: cls dropout 1
aggregator_args:
  p: 0.5

projector: affine 1
projector_args:
  input_dims: 768
  output_dims: 450

comparator: euclidean 1
out: data/test/{text_dataset}/
