# 11GB GPU RAM configuration
# - tested with GTX 1080 TI

# max sequence length: 68
dataloader_train_args:
  batch_size: 500

# max sequence length: 67
dataloader_valid_args:
  batch_size: 500

# max sequence length: 35
dataloader_test_args:
  batch_size: 500
