#
#          RYN TEXT MAPPER CONFIGURATION
#    -----------------------------------------
#
#        see the default.yml for comments
#
valid_split: 0.9
text_encoder: bert-base-cased

split_text_dataset: true

kgc_model: data/kgc/oke.fb15k237_26041992_100/distmult/trial-0017
split_dataset: data/split/oke.fb15k237_26041992_100

wandb_args:
  project: ryn-text
  log_model: false

trainer_args:
  gpus: 1
  check_val_every_n_epoch: 2
  fast_dev_run: false
  distributed_backend: horovod
  accumulate_grad_batches: 10
  gradient_clip_val: 1
  replace_sampler_ddp: false
  log_every_n_steps: 5

checkpoint_args:
  mode: max
  monitor: inductive/hits_at_k/both/avg/10
  save_top_k: 10

dataloader_train_args:
  num_workers: 0
  shuffle: true

dataloader_valid_args:
  num_workers: 0

dataloader_test_args:
  num_workers: 0

optimizer: adam
optimizer_args:
  lr: 1.0e-05

projector_args:
  input_dims: 768
  output_dims: 500

