reductor: independent 1

dataloader_train_args:
  batch_size: 1
  subbatch_size: 30

dataloader_valid_args:
  batch_size: 1
  subbatch_size: 30

dataloader_test_args:
  batch_size: 1
  subbatch_size: 30

